"""create pt_awc_users table

Revision ID: 7b5375668214
Revises: 
Create Date: 2026-02-10 17:34:49.379556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5375668214'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pt_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pt_admins_id'), 'pt_admins', ['id'], unique=False)
    op.create_index(op.f('ix_pt_admins_username'), 'pt_admins', ['username'], unique=True)
    op.create_table('pt_awc_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mobile_number', sa.BigInteger(), nullable=False),
    sa.Column('aadhar_number', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhar_number'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_index(op.f('ix_pt_awc_users_email'), 'pt_awc_users', ['email'], unique=True)
    op.create_index(op.f('ix_pt_awc_users_id'), 'pt_awc_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pt_awc_users_id'), table_name='pt_awc_users')
    op.drop_index(op.f('ix_pt_awc_users_email'), table_name='pt_awc_users')
    op.drop_table('pt_awc_users')
    op.drop_index(op.f('ix_pt_admins_username'), table_name='pt_admins')
    op.drop_index(op.f('ix_pt_admins_id'), table_name='pt_admins')
    op.drop_table('pt_admins')
    # ### end Alembic commands ###
