MAX_LIMIT = 50
DEFAULT_PAGE = 1
TOKEN_EXPIRE_MINUTES = 30
STATUS_ACTIVE = 1
STATUS_INACTIVE = 0
FAKE_VALID_TOKEN = "mysecrettoken"
TOKEN_TYPE = "bearer"
INVALID_EXPIRED_TOKEN="Invalid or expired token"