data = [
    "Paracetamol is used for fever",
    "Ibuprofen reduces pain",
    "Aspirin helps with inflammation",
    "Cough syrup helps in cold",
    "Amoxicillin is used to treat bacterial infections",
    "Metformin helps control blood sugar levels",
    "Cetirizine is used for allergy relief",
    "Omeprazole reduces stomach acid",
    "Azithromycin treats respiratory infections",
    "Vitamin D supports bone health",

    "Insulin regulates blood glucose levels",
    "Dolo 650 is commonly used for fever",
    "Crocin provides relief from mild pain",
    "ORS helps prevent dehydration",
    "Antacids relieve acidity",
    "Loperamide is used for diarrhea",
    "Saline nasal spray relieves nasal congestion",
    "Hydrocortisone cream reduces skin inflammation",
    "Diclofenac reduces joint pain",
    "Naproxen treats muscle pain",

    "Antibiotics should be taken as prescribed",
    "Vaccines help prevent infectious diseases",
    "Inhalers are used for asthma treatment",
    "Painkillers should not be overused",
    "Antihistamines reduce allergic reactions",
    "Probiotics improve gut health",
    "Multivitamins support overall health",
    "Calcium supplements strengthen bones",
    "Iron supplements treat anemia",
    "Zinc boosts immunity",

    "Steam inhalation helps in sinus congestion",
    "Warm salt water gargle relieves sore throat",
    "Drinking fluids helps in recovery from fever",
    "Rest is important during illness",
    "Balanced diet improves immunity",
    "Exercise helps maintain good health",
    "Sleep is essential for recovery",
    "Stress can weaken the immune system",
    "Hygiene prevents infections",
    "Handwashing reduces disease spread",

    "Cold weather can trigger flu symptoms",
    "Hot drinks soothe throat irritation",
    "Honey relieves cough",
    "Ginger helps reduce nausea",
    "Turmeric has anti-inflammatory properties",
    "Garlic boosts immunity",
    "Green tea contains antioxidants",
    "Lemon water aids digestion",
    "Aloe vera soothes skin irritation",
    "Coconut water hydrates the body",

    "Blood pressure should be monitored regularly",
    "Diabetes requires lifestyle management",
    "Cholesterol levels affect heart health",
    "Smoking harms lungs",
    "Alcohol should be consumed in moderation",
    "Regular checkups help early diagnosis",
    "Obesity increases health risks",
    "Mental health is equally important",
    "Meditation reduces stress",
    "Yoga improves flexibility",

    "Eye drops relieve dryness",
    "Hearing aids help with hearing loss",
    "Glucose tablets treat low blood sugar",
    "Bandages protect wounds",
    "Antiseptics prevent infection",
    "Thermometers measure body temperature",
    "Blood tests diagnose diseases",
    "X-rays detect fractures",
    "MRI scans provide detailed imaging",
    "Ultrasound checks internal organs",

    "Kidneys filter waste from blood",
    "Liver detoxifies harmful substances",
    "Heart pumps blood throughout the body",
    "Lungs help in breathing",
    "Brain controls body functions",
    "Nerves transmit signals",
    "Muscles enable movement",
    "Bones provide structure",
    "Skin protects internal organs",
    "Hormones regulate body processes"
]